apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-nodeport
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}
  type: NodePort 